language: ruby
rvm:
 - 2.2
 - jruby
 - rbx-2
env:
  global:
    - CI=true
  matrix:
    - TEST_DOC=false
    - TEST_DOC=true
source :rubygems
gem "bundler"  ,  1.1.3"
gem "rspec"    , "~> 2.8.0"
gem "rake"     , "~> 0.9.2.2"
